#!/usr/bin/env ruby

require 'date'
IMPEDIMENT_TAG = "@impediment"


if ARGV[0] == "usage"
  puts "  Standup Report:"
  puts "    standup [#TERM]"
  puts "      Generates a report of tasks completed \"Yesterday\", and tasks left to do"
  puts "  "

else

  term = ARGV[1]

  today = Date.today
  todays_completed = []
  impediments = []
  open_tasks = []

  # Read done.txt file
  done = File.read(ENV['DONE_FILE'])
  done = done.split($/).sort
  done = done.select { |item| item =~ /#{term}/i }
  done.reverse!

  # Read todo.txt file
  todo = File.read(ENV['TODO_FILE'])
  todo = todo.split($/).sort
  todo = todo.select { |item| item =~ /#{term}/i }

  # sort todo items into impediments and normal tasks 
  todo.each { |task| 
    if task.include?(IMPEDIMENT_TAG)
      impediments.push(task)
    else
      open_tasks.push(task) 
    end
  }
 
  # define 'yesterday' as the last date on the done file that is not 'today'
  i = 0
  begin
      data = /x\s(?<date>\d{4}-\d{2}-\d{2})\s(?<task>.*)/.match(done[i]);
      break unless data
      yesterday  = Date.strptime(data[:date], '%Y-%m-%d')
      i += 1
  end until today != yesterday

  # ==============================
  # Print out tasks
  # ==============================

  puts "\n"

  if done.length > 0
    puts "========================================"
    puts " Completed Yesterday: #{yesterday}"
    puts "========================================"
    done.each { |item|
      data =  /x\s(?<date>\d{4}-\d{2}-\d{2})\s(?<task>.*)/.match(item)
      task_date = Date.strptime(data[:date], '%Y-%m-%d')
      if task_date == yesterday 
        puts "+ #{data[:task]}"
      elsif task_date == today
        todays_completed.push(data[:task])       
      end
    }
    puts "\n"
  end

  if todays_completed.length > 0
    puts "========================================"
    puts " Completed Today: #{Date.today}"
    puts "========================================"
    todays_completed.each { |task|
      puts "+ #{task}"
    }
    puts "\n"
  end

  if open_tasks.length > 0 
    puts "========================================"
    puts " Open Tasks"
    puts "========================================"
    open_tasks.each { |task|
      puts "- #{task}"
    }
    puts "\n"
  end

  if impediments.length > 0
    puts "\n========================================"
    puts " Impediments: #{Date.today}"
    puts "========================================"
    impediments.each { |task|
      puts"i #{task}"
    }
    puts "\n"
  end
end
